object Versions {
    const val COMMONS_LOGGING = "1.3.5"
    const val COMMONS_NUMBERS = "1.2"
    const val COROUTINES = "1.10.2"
    const val GOOGLE_TRUTH = "1.4.4"
    const val JUNIT = "5.12.1"
    const val JUNIT_PLATFORM = "1.12.1"
    const val KOTLIN = "2.1.20"
    const val KOTLINX_DATETIME = "0.6.2"
    const val KOTLINX_SERIALIZATION = "1.8.1"
    const val KTLINT = "1.5.0"
    const val KTLINT_PLUGIN = "12.2.0"
    const val KTOR = "3.1.2"
    const val LOGBACK = "1.5.18"
    const val MAVEN_REPO_AUTH_PLUGIN = "3.0.4"
    const val MOCKK = "1.14.0"
    const val VERSIONS_PLUGIN = "0.52.0"
}
