object Versions {
    const val COMMONS_LOGGING = "1.3.1"
    const val COMMONS_NUMBERS = "1.1"
    const val COROUTINES = "1.8.0"
    const val GOOGLE_TRUTH = "1.4.2"
    const val JUNIT = "5.10.2"
    const val KOTLIN = "1.9.23"
    const val KOTLINX_DATETIME = "0.5.0"
    const val KOTLINX_SERIALIZATION = "1.6.3"
    const val KTLINT = "1.2.1"
    const val KTLINT_PLUGIN = "12.1.0"
    const val KTOR = "2.3.9"
    const val LOGBACK = "1.5.3"
    const val MAVEN_REPO_AUTH_PLUGIN = "3.0.4"
    const val MOCKK = "1.13.10"
    const val VERSIONS_PLUGIN = "0.51.0"
}
