object Versions {
    const val COMMONS_LOGGING = "1.3.5"
    const val COMMONS_NUMBERS = "1.2"
    const val COROUTINES = "1.10.2"
    const val GOOGLE_TRUTH = "1.4.5"
    const val JUNIT = "6.0.2"
    const val JUNIT_PLATFORM = "6.0.2"
    const val KOTLIN = "2.3.0"
    const val KOTLINX_SERIALIZATION = "1.10.0"
    const val KTLINT = "1.8.0"
    const val KTLINT_PLUGIN = "14.0.1"
    const val KTOR = "3.4.0"
    const val LOGBACK = "1.5.27"
    const val MOCKK = "1.14.9"
    const val MAVEN_PUBLISH = "0.36.0"
    const val VERSIONS_PLUGIN = "0.53.0"
}
